apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: advertisement-namespace
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /var/lib/postgresql/data
